
package one.microstream.microstreamtraining.ui;

import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;

import one.microstream.microstreamtraining.business.storage.StorageUtils;
import one.microstream.microstreamtraining.entities.Customer;

public class MainView extends XdevView {

	/**
	 * 
	 */
	public MainView() {
		super();
		this.initUI();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #btnSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnSave_buttonClick(final Button.ClickEvent event) {
		final Customer customer = new Customer();
		customer.setFirstname(this.txtFirstname.getValue());
		customer.setLastname(this.txtLastname.getValue());
		
		StorageUtils.ROOT.get().setCustomer(customer);
		StorageUtils.STORAGE.store(StorageUtils.ROOT.get());
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #btnLoad}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnLoad_buttonClick(final Button.ClickEvent event) {
		final Customer customer = StorageUtils.ROOT.get().getCustomer();
		this.lblFirstname.setValue(customer.getFirstname());
		this.lblLastname.setValue(customer.getLastname());
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.btnSave = new XdevButton();
		this.btnLoad = new XdevButton();
		this.txtFirstname = new XdevTextField();
		this.lblFirstname = new XdevLabel();
		this.txtLastname = new XdevTextField();
		this.lblLastname = new XdevLabel();
	
		this.btnSave.setCaption("Speichern");
		this.btnLoad.setCaption("Laden");
		this.lblFirstname.setValue("Label");
		this.lblLastname.setValue("Label");
	
		this.gridLayout.setColumns(2);
		this.gridLayout.setRows(4);
		this.btnSave.setWidth(100, Unit.PERCENTAGE);
		this.btnSave.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.btnSave, 0, 0);
		this.btnLoad.setWidth(100, Unit.PERCENTAGE);
		this.btnLoad.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.btnLoad, 1, 0);
		this.txtFirstname.setWidth(100, Unit.PERCENTAGE);
		this.txtFirstname.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.txtFirstname, 0, 1);
		this.lblFirstname.setSizeUndefined();
		this.gridLayout.addComponent(this.lblFirstname, 1, 1);
		this.gridLayout.setComponentAlignment(this.lblFirstname, Alignment.MIDDLE_LEFT);
		this.txtLastname.setWidth(100, Unit.PERCENTAGE);
		this.txtLastname.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.txtLastname, 0, 2);
		this.lblLastname.setSizeUndefined();
		this.gridLayout.addComponent(this.lblLastname, 1, 2);
		this.gridLayout.setComponentAlignment(this.lblLastname, Alignment.MIDDLE_LEFT);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setColumnExpandRatio(1, 10.0F);
		final CustomComponent gridLayout_vSpacer = new CustomComponent();
		gridLayout_vSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_vSpacer, 0, 3, 1, 3);
		this.gridLayout.setRowExpandRatio(3, 1.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	
		this.btnSave.addClickListener(event -> this.btnSave_buttonClick(event));
		this.btnLoad.addClickListener(event -> this.btnLoad_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton btnSave, btnLoad;
	private XdevLabel lblFirstname, lblLastname;
	private XdevGridLayout gridLayout;
	private XdevTextField txtFirstname, txtLastname;
	// </generated-code>

}
